# Site settings
title: theSkullery
email: robert@nhg.design
description: A scullery is a historical noun for a small kitchen, much like mine.
baseurl: ""
language: "en"
lang_direction: "ltr"
color: "#E83151"
twitter_username: robcsaszar
github_username: robcsaszar
timezone: Europe/Bucharest


# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true
  chef:
    output: true
  meal:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
