var encodedData = btoa(JSON.stringify(localStorage));
console.log(encodedData)

var unencodedData = atob('eyI8YSBjbGFzcz1cInBhZ2UtLWxpc3RpdGVtXCIgaHJlZj1cImh0dHA6Ly9sb2NhbGhvc3Q6NDAwMC9yZWNpcGVzL21vbW9mdWt1LXN0ZWFtZWQtYnVucy9cIj48c3ZnIGNsYXNzPVwibGlzdGl0ZW0tLWljb25cIiB4bWxucz1cImh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnXCIgeG1sbnM6eGxpbms9XCJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rXCIgdmlld0JveD1cIjAgMCAyNCAyNFwiIHdpZHRoPVwiMjRweFwiPjxwYXRoIGQ9XCJNMjAsMjJsLTgtM2wtOCwzVjRjMC0xLjEwNSwwLjg5NS0yLDItMmgxMmMxLjEwNSwwLDIsMC44OTUsMiwyVjIyelwiLz48cGF0aCBkPVwiTTE4LDJINkM0LjksMiw0LjAxLDIuOSw0LjAxLDRMNCwyMmw4LTNsOCwzVjRDMjAsMi45LDE5LjEsMiwxOCwyelwiLz48L3N2Zz5Nb21vZnVrdSBTdGVhbWVkIEJ1bnM8L2E+IjoiZmF2b3JpdGUifQ==');
var data = JSON.parse(unencodedData);
Object.keys(data).forEach(function (k) {
  localStorage.setItem(k, data[k]);
});
